### PR TITLE
transfer all modes in LunaPulse

### PR DESCRIPTION
**Pull request by chrisbrahms**
As it says on the tin: instead of just transferring the fundamental mode, make `LunaPulse`s transfer all modes. Only works if the modes in the two simulations are exactly the same. 

Energy in the transferred field can be defined in a few different ways by keyword arguments to `LunaPulse`
1. No arguments given: full energy is transferred from one sim to the next
2. `energy` given: total energy is scaled to this value
3. `scale_energy` given as `Number`: total energy is scaled by this factor
4. `scale_energy` given as `Vector`: energy in each mode is scaled differently

TODO:

- [x] Think about possible edge cases
- [x]  Add tests to check that correct and understandable exceptions are thrown

CC @nkotsina @martgebhardt

### CODE REVIEW

**Review by jtravs — APPROVED** [review]
LGTM, assuming the rather good set of tests pass.

One minor thing: sometimes it was nice to be able to couple to a sim with fewer modes (well, just to the fundamental as previously implemented). Maybe there could be an option to allow this if specifically asked for?

**Comment by chrisbrahms** [comment]
> One minor thing: sometimes it was nice to be able to couple to a sim with fewer modes (well, just to the fundamental as previously implemented). Maybe there could be an option to allow this if specifically asked for?

This is already possible by giving `scale_energy` as a vector and setting all other elements to zero. If that's too inconvenient I can add an explicit "cropping" functionality but I'm not sure it's necessary?

**Comment by chrisbrahms** [comment]
Or do you mean coupling to a sim in which fewer modes _exist_?

**Comment by jtravs** [comment]
> Or do you mean coupling to a sim in which fewer modes _exist_?

Yes. I have done that before, but I agree it is fringe, and is also possible "by hand" so I wouldn't add it here.

**Comment by chrisbrahms** [comment]
> > Or do you mean coupling to a sim in which fewer modes _exist_?
> 
> Yes. I have done that before, but I agree it is fringe, and is also possible "by hand" so I wouldn't add it here.

Yes, the way to do that would be to simply crop the array of pulses since `LunaPulse` just returns an array of `DataPulse`s

**Pull request merged**
