### PR TITLE
Step-index fibres

### PR DESCRIPTION
**Pull request by chrisbrahms**
Branch copied from @jtravs and merged with current master. No other changes yet. Still lots of to-dos:

- [x] Deal with this in `Raman.jl`
```
    elseif rp.kind == :intermediate
        # TODO: scale argument is hardcoded to 1.0 here!
        return RamanRespIntermediateBroadening(rp.ωi, rp.Ai, rp.Γi, rp.γi, 1.0)
```

- [x] `neff` for `SimpleFibre` doesn't include loss
- [ ] Frequency dependence of step-index fibre modes (this is the big one...)

### CODE REVIEW

**Comment by jtravs** [comment]
In theory, there is zero loss for step-index fibres apart from material absorption. I suspect, for the purposes of this we can assume this to be negligible? Or I suppose a user can specify some arbitrary non-zero loss value (or function)?

**Comment by chrisbrahms** [comment]
My point is just that for a `SimpleMode`, the user can supply a value for `α`:
```julia
function SimpleMode(ωref, βs; Aeff=1.0, loss=0.0)
```
and the function `α` returns this:
```julia
α(m::SimpleMode, ω; z=0.0) = m.α
```
but it's not included in `neff`:
```julia
neff(m::SimpleMode, ω; z=0) = c/ω*β(m, ω, z=z)
```

**Comment by chrisbrahms** [comment]
I got that. For χ3 I agree with you. But my issue is that `γ3` is the symbol for the (single-particle) hyperpolarisability, which only really makes sense for gases since their density can change. In other words, most of the time the user would call `χ3` anyway which switches depending on the material type, and `γ3` is more often than not a purely internal function.

**Comment by chrisbrahms** [comment]
It took a bit of fixing to integrate this with more recent changes to the Raman code, but I think it's ready to be double-checked and merged now.

Just to check, @jtravs , this is the result of the comparison in `stepsimplecmp.jl` after I've fixed it:
image

Is this similar to what you got before? The polynomial fit of β to get the dispersion coefficients doesn't work and I couldn't fix it (not sure why) so I used `Modes.dispersion` instead.

**Comment by jtravs** [comment]
Just a note that I haven't suggested merging this yet because it doesn't reproduce some of my existing GNLSE code (and is slower). 

For example, running the example `examples/simple_interface/gnlse_scg.jl` should reproduce `testdudley.py` from https://github.com/LupoLab/SimpleGnlse but it misses from XPM between the Raman soliton and RDW. I'm fairly confident of the GNLSE code, so I think something is up with the Luna code, but it needs more time to search this out. I'm guessing just the Raman shift rate.

**Comment by jtravs** [comment]
> Is this similar to what you got before? The polynomial fit of β to get the dispersion coefficients doesn't work and I couldn't fix it (not sure why) so I used `Modes.dispersion` instead.

That's weird if the polynomial fit previously worked. Was there an update to that code in between?

**Comment by jtravs** [comment]
Out of time at the moment, but I realized that my GNLSE code I'm comparing to used just an SDO Raman model. I have added this to the gnlse interface of Luna, but it doesn't currently work; must be a small bug somewhere. I'm pretty sure that this was the cause of the discrepancy though.

**Comment by jtravs** [comment]
OK, I fixed the SDO interface, and it turns out that this wasn't sufficient. So it must be something else.

**Comment by chrisbrahms** [comment]
> > Is this similar to what you got before? The polynomial fit of β to get the dispersion coefficients doesn't work and I couldn't fix it (not sure why) so I used `Modes.dispersion` instead.
> 
> That's weird if the polynomial fit previously worked. Was there an update to that code in between?

It is weird. Had another look, and it seems that it does work if I scale the `ωs` by `1e-15` to bring the x values to around 1 (which makes the coefficients much bigger):
image

**Comment by chrisbrahms** [comment]
New comparison in `stepsimplecmp.jl` after going back to polynomial fit
image

**Comment by jtravs** [comment]
OK @chrisbrahms this is now fixed. I have also added a few gnlse tests and edited the README. You might want to review the changes to check you are happy with them. From my side I think this can be merged (assuming tests pass).

**Review by jtravs — APPROVED** [review]

**Comment by chrisbrahms** [comment]
just found some very minor typos. I don't quite understand what the problem was so I'll ask you to explain at some point, but no need to write it all down.

**Pull request merged**
